version = "2"

[com]
protocol = "uds"
socket_path = "/tmp/termusic.socket"
port = 50101
address = "::1"

[player]
music_dirs = ["/home/turip/unorg", "/mnt/usb"]
remember_position = "yes"
loop_mode = "playlist"
volume = 100
speed = 10
gapless = true
use_mediacontrols = true
set_discord_status = true
random_track_quantity = 100
random_album_min_quantity = 5
backend = "rusty"

[player.seek_step]
short_tracks = 5
long_tracks = 30

[podcast]
concurrent_downloads_max = 3
max_download_retries = 5
download_dir = "/home/turip/unorg"

[backends.rusty]
soundtouch = true
file_buffer_size = "4.0 MiB"
decoded_buffer_size = "750.0 KiB"
output_sample_rate = 48000

[backends.mpv]
audio_device = "auto"

[metadata]
directory_scan_depth = 10
artist_separators = [",", ";", "&", "ft.", "feat.", "/", "|", "×", "、", " x "]
