version = "2"
com = "same"

[behavior]
quit_server_on_exit = true
confirm_quit = true

[coverart]
align = "bottom right"
size_scale = 0
hidden = false
protocols = ["sixel", "ueberzug", "kitty", "iterm2"]

[style.library]
foreground_color = "Foreground"
background_color = "Reset"
border_color = "Blue"
highlight_color = "LightYellow"
highlight_symbol = "ðŸ¦„"

[style.playlist]
foreground_color = "Foreground"
background_color = "Reset"
border_color = "Blue"
highlight_color = "LightYellow"
highlight_symbol = "ðŸš€"
current_track_symbol = "â–º"
use_loop_mode_symbol = true

[style.lyric]
foreground_color = "Foreground"
background_color = "Reset"
border_color = "Blue"

[style.progress]
foreground_color = "LightBlack"
background_color = "Reset"
border_color = "Blue"

[style.important_popup]
foreground_color = "Yellow"
background_color = "Reset"
border_color = "Yellow"

[style.fallback]
foreground_color = "Foreground"
background_color = "Reset"
border_color = "Blue"
highlight_color = "LightYellow"

[theme]
file_name = "Baskerville - FarSide"
name = "FarSide"
author = "Baskerville"

[theme.primary]
background = "#000000"
foreground = "#919191"

[theme.cursor]
text = "#000000"
cursor = "#919191"

[theme.normal]
black = "#303030"
red = "#a43261"
green = "#006ca5"
yellow = "#007086"
blue = "#6751a6"
magenta = "#913e88"
cyan = "#0061b1"
white = "#c6c6c6"

[theme.bright]
black = "#5e5e5e"
red = "#ff9fc9"
green = "#3bd6ff"
yellow = "#00ddf4"
blue = "#d5b8ff"
magenta = "#ffa7f6"
cyan = "#93c9ff"
white = "#ffffff"

[keys]
escape = "escape"
quit = "q"

[keys.view]
view_library = "1"
view_database = "2"
view_podcasts = "3"
open_config = "shift+C"
open_help = "control+h"

[keys.navigation]
up = "k"
down = "j"
left = "h"
right = "l"
goto_top = "shift+K"
goto_bottom = "shift+J"

[keys.global_player]
toggle_pause = "space"
next_track = "n"
previous_track = "shift+N"
volume_up = "+"
volume_down = "-"
seek_forward = "f"
seek_backward = "b"
speed_up = "control+f"
speed_down = "control+b"
toggle_prefetch = "control+g"
save_playlist = "control+s"

[keys.global_lyric]
adjust_offset_forwards = "shift+F"
adjust_offset_backwards = "shift+B"
cycle_frames = "shift+T"

[keys.library]
load_track = "l"
load_dir = "shift+L"
delete = "d"
yank = "y"
paste = "p"
cycle_root = "o"
add_root = "a"
remove_root = "shift+A"
search = "/"
youtube_search = "s"
open_tag_editor = "t"

[keys.playlist]
delete = "d"
delete_all = "shift+D"
shuffle = "s"
cycle_loop_mode = "m"
play_selected = "l"
search = "/"
swap_up = "shift+K"
swap_down = "shift+J"
add_random_songs = "control+shift+S"
add_random_album = "shift+S"

[keys.database]
add_selected = "l"
add_all = "shift+L"

[keys.podcast]
search = "alt+s"
mark_played = "m"
mark_all_played = "shift+M"
refresh_feed = "r"
refresh_all_feeds = "shift+R"
download_episode = "d"
delete_local_episode = "shift+D"
delete_feed = "x"
delete_all_feeds = "shift+X"

[keys.adjust_cover_art]
move_left = "control+shift+arrowleft"
move_right = "control+shift+arrowright"
move_up = "control+shift+arrowup"
move_down = "control+shift+arrowdown"
increase_size = "control+shift+pageup"
decrease_size = "control+shift+pagedown"
toggle_hide = "control+shift+end"

[keys.config]
save = "control+s"

[ytdlp]
extra_args = ""
