[pyprland]
 plugins = ["expose"] #also add "wallpapers"

[expose]
include_special = true

#[wallpapers]
#unique = true # set a different wallpaper for each screen
#path = "~/pictures/anastasia/"
#interval = 5 # change every hour
#extensions = ["jpg", "jpeg"]
#recurse = true
#clear_command = "swww clear"
